Repository eurofurence/crittersystem, pull requests merged in 2024-09, with the labels that each got.

#25 fix(user): ltrim @ from dectelegram on create
  src/Controllers/SettingsController.php
  src/Factories/User.php
Labels: bug

#46 Fix issue #19
  includes/view/ShiftCalendarRenderer.php
Labels: enhancement

#47 Bugfix #13 - fix the back button
  includes/pages/user_shifts.php
Labels: bug

#53 Added some custom client-side form validation
  resources/assets/js/forms.js
  resources/assets/themes/base.scss
  resources/views/macros/form.twig
  resources/views/pages/registration.twig
Labels: Discussion

#61 Bugfix and Docker adjustment
  .dockerignore
  .gitattributes
  docker/Dockerfile
  docker/config/nginx.conf
  docker/config/opcache.ini
  docker/config/www.conf
  includes/helper/legacy_helper.php
Labels: bug, enhancement
